# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetMeThePSI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetMeThePSI
  pod 'SHSnackBarView'
  pod 'SwiftSpinner'
  
  target 'GetMeThePSITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetMeThePSIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
